---

- name: Update package cache and install mysql-server
  hosts: all
  gather_facts: no
  become: true
  become_user: root

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install mysql-server
      ansible.builtin.apt:
        name: mysql-server
        state: present
