---

- hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_pass: 123

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install mysql-server
      ansible.builtin.apt:
        name: mysql-server
        state: present
